device: cuda
precision: 64
seed: null
simulation_dir: ???
overwrite: false
restart: null

defaults:
  - calculator: schnetpack
  - system: system
  - dynamics: nve
  - logging: basic

hydra:
  run:
    dir: ${simulation_dir}
  job:
    config:
      override_dirname:
        exclude_keys:
          - basename
        kv_sep: '='
        item_sep: '_'