device: cuda
precision: 32
seed: null
simulation_dir: ???
overwrite: false
retart: null

defaults:
  - calculator: schnetpack
  - system: system
  - dynamics: nve
#  - callbacks: default_callbacks
#  - model: null
#  - data: null
#  - logger: null


hydra:
  run:
    dir: ${simulation_dir}
  job:
    config:
      override_dirname:
        exclude_keys:
          - basename
        kv_sep: '='
        item_sep: '_'